version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    container_name: postgress
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8585:8080